
public class Finally {
    public static void main(String[] args) {
    	
        try {
            int a = 10;
            int b = 0;
            int result = a / b;  // ‚ùå This will throw ArithmeticException
            System.out.println("Result: " + result);
        } catch (ArithmeticException e) {
            System.out.println("Exception caught: " + e);
        } finally {
            // Always executed
            System.out.println("Finally block executed");
        }

        System.out.println("Program continues after try-catch-finally...");
    }
}
//finally block executes even if shows error or not